# Generated by Django 4.2.5 on 2023-10-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
