# Generated by Django 4.2.5 on 2023-10-04 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('n_cuenta', models.CharField(default='XXXX', max_length=50, primary_key=True, serialize=False)),
                ('tipo_cuenta', models.CharField(default='AHORROS', max_length=20)),
                ('saldo', models.FloatField(default=0)),
                ('titular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
