# Generated by Django 4.2.5 on 2023-10-04 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2023, 10, 3))),
                ('valor', models.FloatField()),
                ('n_cuenta', models.ManyToManyField(to='cuenta.cuenta')),
            ],
        ),
    ]
