# Generated by Django 4.2.5 on 2023-10-04 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 13, 34, 15, 198451, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='n_cuenta',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='n_cuenta',
            field=models.ForeignKey(default=datetime.datetime(2023, 10, 4, 13, 34, 33, 679542, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='cuenta.cuenta'),
            preserve_default=False,
        ),
    ]
